[package]
name = "sloth"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam = "0.8.4"

[dev-dependencies]
criterion = { version = "0.8.1", features = ["html_reports"] }

[[bench]]
name = "cache_benchmark"
harness = false
